# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-25 04:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 9, 24, 23, 43, 13, 354187)),
            preserve_default=False,
        ),
    ]
