# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-25 05:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('album', '0002_photo_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='allowed_users',
            field=models.ManyToManyField(related_name='invited_albums', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='album',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_albums', to=settings.AUTH_USER_MODEL),
        ),
    ]
